name: busca_cep_flutter
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  retrofit: ^4.4.0
  logger: ^2.4.0 # for logging purpose
  json_annotation: ^4.9.0
  drift: ^2.22.1
  drift_flutter: ^0.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  retrofit_generator: ">=8.0.0 <10.0.0" # for Dart 3.3 use ^9.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  drift_dev: ^2.22.1

flutter:
  uses-material-design: true
